os: osx

language: node_js

node_js:
  - "8"

install:
  - yarn

before_script:
  - npm install -g solium
  - npm install -g truffle

script:
  - yarn lint
  - solium -d contracts
  - truffle compile

cache:
  directories:
  - node_modules