export const chatActionType = {
    SET_WEB3_INSTANCE_SUCCESS: 'SET_WEB3_INSTANCE_SUCCESS',
    SET_WEB3_INSTANCE_FAILURE: 'SET_WEB3_INSTANCE_FAILURE',
    GET_SPACES_SUCCESS: 'GET_SPACES_SUCCESS',
    GET_SPACES_FAILURE: 'GET_SPACES_FAILURE',
};
